### PR TITLE
S2A & S2B relative spectral response function

### PR DESCRIPTION
**Pull request by MarcYin**
This updates Sentinel-2A spectral responses and changes are mainly modifying the responses for bands B01 and B02, which is important for the aerosol retrieval. The sentinel 2B relative spectral response functions are also added.

### CODE REVIEW

**Comment by robintw** [comment]
Thanks for submitting this PR.

In general, I'm happy to accept it - but I'm wondering why you have changed the names of the spectral response functions? Eg. `S2A_SR_AV_B01` rather than `S2A_MSI_01`?

**Comment by MarcYin** [comment]
That's the name specified in the official spectral response function file and it's averaged values of measured spectral responses for each band of the Sentinel-2 MultiSpectral Instrument (MSI) for the different satellite units, which explains why it has `_AV_` in each band. But if you want still use the original names, we can roll back to previous names.

**Comment by robintw** [comment]
Ah yeah, I see where they come from.

I think the original names would be better (for both S2A and S2B) - it'd save changing other bits of the code, or other people's code.

**Comment by MarcYin** [comment]
Ok, I have changed it and fixed the indexes overlaps between different sensors.

**Comment by robintw** [comment]
Is this fixed by #50?

**Comment by MarcYin** [comment]
Hi, this should have been fixed in  #51

**Pull request closed without merging**
