### PR TITLE
Add Sentinel-3B SLSTR spectral response functions and S3B helpers

### PR DESCRIPTION
**Pull request by lwandrebeck**

### CODE REVIEW

**Comment by robintw** [comment]
Hi, thanks for the PR.

The Continuous Integration tests aren't passing at the moment, and they're failing on the `S3B_SLSTR_05` wavelength definition, and the error suggests it's because the wavelengths aren't at 2.5nm intervals.

If you could check that definition is correct and at 2.5nm intervals, then that'd be great.

**Comment by lwandrebeck** [comment]
Hi,

Just checked with the scientist who generated this, there was indeed an error, which should be fixed now.

**Comment by lwandrebeck** [comment]
Small fix for S3B_SLSTR_06 added.

**Comment by lwandrebeck** [comment]
Sorry for the noise, everything should be ok now.

**Comment by robintw** [comment]
Thanks - that's great. All tests pass, and I'll merge it now.

Thanks for your contribution!

**Pull request merged**
