### PR TITLE
Fixes for Python 3

### PR DESCRIPTION
**Pull request by danclewley**
Fixes for compatibility to Python 3 without breaking compatibility with Python 2.7. 
Ran all unit tests:

3 Errors 2 Failures under Python 3.4
2 Errors 2 Failures under Python 2.7 (Same as master, running under 64 bit CentOS 6.5 Linux)

### CODE REVIEW

**Comment by robintw** [comment]
Hi Dan - I haven't had chance to have a look at this in depth, but I'm a little confused as I have automated tests running every time I commit any changes, and these show that all of the tests pass on both Python 2.7 and 3.4. I also definitely remember doing a lot of the changes that you've done myself a while back...

I'll try and work out what's happening later on this week (I've got my PhD corrections to do before then - I had my viva last week and passed with minor corrections), and then get back to you. It could be some strange thing I've done with git branches or something..

**Comment by danclewley** [comment]
Hi Robin
I've not been able to install the latest version with Python 3. I think some of the changes that @petebunting made for Python 3 were reverted in commit b0c4c392450d1d7bde9568817cf56d9bbdbc85df. Some of them would have broken compatibility with Python 2 so I've added a lot more checks for the Python version this time.

No rush on this, I started looking at it a while ago for our conda builds (https://binstar.org/osgeo/py6s/) and thought it would be a good idea to tidy up and get a pull request submitted.

Well done on passing your Viva!

**Comment by petebunting** [comment]
Hi Robin, 

Using the latest repo version I get the follow errors which I think Dan has fixed here:

  File "build/bdist.macosx-10.5-x86_64/egg/Py6S/lut_trial.py", line 26
    print res
            ^
SyntaxError: Missing parentheses in call to 'print'

  File "build/bdist.macosx-10.5-x86_64/egg/Py6S/outputs.py", line 62
    print stderr
               ^
SyntaxError: Missing parentheses in call to 'print'

  File "build/bdist.macosx-10.5-x86_64/egg/Py6S/sixs.py", line 316
    print "Py6S Debugging Report"
                                ^
SyntaxError: Missing parentheses in call to 'print'

  File "build/bdist.macosx-10.5-x86_64/egg/Py6S/SixSHelpers/all_angles.py", line 84
    print "Running for many angles - this may take a long time"
                                                              ^
SyntaxError: Missing parentheses in call to 'print'

  File "build/bdist.macosx-10.5-x86_64/egg/Py6S/SixSHelpers/all_wavelengths.py", line 65
    print wv
           ^
SyntaxError: Missing parentheses in call to 'print'

Hope that helps. 

Cheers, Pete

**Comment by robintw** [comment]
Thanks for all your help on this - I've now merged this, with a few changes, and done a few other alterations and Py6S now seems to properly support Python 3.

I've now released v1.6, and will be sending an email around the mailing list shortly.

Thanks!

**Pull request merged**
