### PR TITLE
Renamed the S2A band names and added S2B RSRs

### PR DESCRIPTION
**Pull request by MarcYin**
Renamed the S2A band names and added S2B RSRs, also changed the index of S3B RSRs to make it consistent with the oder of: S2A, S3A_OLCI, S3A_SLSTR, S2B, S3B_OLCI.

### CODE REVIEW

**Comment by robintw** [comment]
Hi - I'm trying to sort out various PRs for Py6S now, and can see three PRs from you about Sentinel spectral responses (#39, #40 and this one). Does this one (the most recently submitted), supersede the others?

Also, a few questions/comments:

1. Could you add a comment with the source of the spectral response function data that you used to generate these SRFs?

2. Why have you renamed the constants from something like `S2A_MSI_01` to `S2A_SR_AV_B1`? The problem with renaming the constants is that it will break people's code that is based on a previous version of Py6S - and that's something I try to avoid where possible.

**Comment by MarcYin** [comment]
Yes, this one suppresses the others.

The source of this spectral response function is from Sentinel 2 official website: [https://earth.esa.int/web/sentinel/user-guides/sentinel-2-msi/document-library/-/asset_publisher/Wk0TKajiISaR/content/sentinel-2a-spectral-responses](url)

The reason for changing the name is because I just used the same naming convention from the original Sentinel 2 spectral response function file. There is one band named as B8A, which is weird  ... but it is used for all the Sentinel 2 files and the original Py6S named it as band 9, which make it a bit confusing sometimes... so I would rather stick with the official naming conventions.

**Comment by robintw** [comment]
Thanks @MarcYin. I've merged the PR, but modified the names of the bands so that they match the names used for all the other sensors in Py6S - that is `<satellite>_<sensor>_<band>`. In this case, that's `S2A_MSI_B01` etc. Thanks for pointing out the issue with Band 8A - I've kept that in there.

I've also added the source - although I forgot to do that in the merge, so added it as a separate commit later.

Thanks for contributing, and sorry for the very slow merge - life somewhat took over!

**Comment by MarcYin** [comment]
Happy to contribute to this great work!

**Pull request merged**
